apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
spec:
  template:
    spec:
      containers:
        - name: mongo
          image: mongo
          command: ['mongo']
          args:
            - "--eval"
            - >
              db.createUser({
                user: 'admin',
                pwd: 'password',
                roles: [{ role: 'readWrite', db: 'mydatabase' }]
              });
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 27017
      restartPolicy: OnFailure
